tasks_plugin:
  name: whi_waypoints_tasks_plugin/WaypointsTasks
  service: tcp_pose
  base_frame: ur10e_base_link
  tcp_frame: camera
  detection_topic: /yolov5/detections
  pixel_size: 0.000003 # m
  focal_length: 0.00193 # m
  state_topic: actuator_state
