tasks_plugin:
  name: whi_waypoints_tasks_plugin/WaypointsTasks
  service: tcp_pose
  base_frame: ur10e_base_link
  tcp_frame: camera
  detection_topic: /yolov5/detections
  pixel_size: 0.000003 # m
  focal_length: 0.00193 # m
  depth_multiplier: 1.0
  locating_duration: 1200 # ms
  locating_tolerance: 0.003 # m
  locating_velocity_scale: 1.0
  locating_acceleration_scale: 0.5
  exception_pose_group: ready
  state_topic: actuator_state
