tasks_plugin:
  name: whi_waypoints_tasks_plugin/WaypointsTasks
  service: /whi/ur_combined/whi_moveit_cpp_bridge/tcp_pose
  estop_topic: /estop
  alignment_timeout: 15 # unit second
  base_frame: whi/base_link
  tcp_frame: whi/camera
  detection_topic: /pgnd_inspection
  pixel_size: 0.000003 # m
  focal_length: 0.00193 # m
  depth_multiplier: 1.0
  state_topic: actuator_state
  installation_to_tcp: [90.0, 0, 0] # degrees
  debug:
    print_locating_error: true
